//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersAndCandyCustomer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowersAndCandyCustomer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection..
        /// </summary>
        internal static string _connection {
            get {
                return ResourceManager.GetString("_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Verification.
        /// </summary>
        internal static string _otpVerification {
            get {
                return ResourceManager.GetString("_otpVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 10 Digits Phone Number.
        /// </summary>
        internal static string _phonevalidation {
            get {
                return ResourceManager.GetString("_phonevalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your fourth digit.
        /// </summary>
        internal static string _youFrourthDigit {
            get {
                return ResourceManager.GetString("_youFrourthDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your fifth digit.
        /// </summary>
        internal static string _yourFifthDigit {
            get {
                return ResourceManager.GetString("_yourFifthDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first digit.
        /// </summary>
        internal static string _yourFirstDigit {
            get {
                return ResourceManager.GetString("_yourFirstDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your second digit.
        /// </summary>
        internal static string _yourSecondDigit {
            get {
                return ResourceManager.GetString("_yourSecondDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your third digit.
        /// </summary>
        internal static string _yourThirdDigit {
            get {
                return ResourceManager.GetString("_yourThirdDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        internal static string add_address {
            get {
                return ResourceManager.GetString("add_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Delivery Address.
        /// </summary>
        internal static string add_delivery_address {
            get {
                return ResourceManager.GetString("add_delivery_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Order.
        /// </summary>
        internal static string add_order {
            get {
                return ResourceManager.GetString("add_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Addon.
        /// </summary>
        internal static string addAddon {
            get {
                return ResourceManager.GetString("addAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More.
        /// </summary>
        internal static string addmore {
            get {
                return ResourceManager.GetString("addmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string addnote {
            get {
                return ResourceManager.GetString("addnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Adddon Category Name.
        /// </summary>
        internal static string addoncategoryname {
            get {
                return ResourceManager.GetString("addoncategoryname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Product Price.
        /// </summary>
        internal static string addonLPrice {
            get {
                return ResourceManager.GetString("addonLPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Product Price.
        /// </summary>
        internal static string addonMPrice {
            get {
                return ResourceManager.GetString("addonMPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add On Name.
        /// </summary>
        internal static string addonName {
            get {
                return ResourceManager.GetString("addonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string addonQty {
            get {
                return ResourceManager.GetString("addonQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ons.
        /// </summary>
        internal static string addons {
            get {
                return ResourceManager.GetString("addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Product Price.
        /// </summary>
        internal static string addonSPrice {
            get {
                return ResourceManager.GetString("addonSPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        internal static string addProduct {
            get {
                return ResourceManager.GetString("addProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address.
        /// </summary>
        internal static string addressList {
            get {
                return ResourceManager.GetString("addressList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shop.
        /// </summary>
        internal static string addShop {
            get {
                return ResourceManager.GetString("addShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        internal static string addToCart {
            get {
                return ResourceManager.GetString("addToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add to cart?.
        /// </summary>
        internal static string addtocart_text {
            get {
                return ResourceManager.GetString("addtocart_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read &amp; agree with the .
        /// </summary>
        internal static string agree_with_terms {
            get {
                return ResourceManager.GetString("agree_with_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string already_have_account {
            get {
                return ResourceManager.GetString("already_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        internal static string buy_now {
            get {
                return ResourceManager.GetString("buy_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candy.
        /// </summary>
        internal static string candy {
            get {
                return ResourceManager.GetString("candy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string card {
            get {
                return ResourceManager.GetString("card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Holder Name.
        /// </summary>
        internal static string CardHolderName {
            get {
                return ResourceManager.GetString("CardHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Cart.
        /// </summary>
        internal static string cartPage {
            get {
                return ResourceManager.GetString("cartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string cash {
            get {
                return ResourceManager.GetString("cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose From Gallery.
        /// </summary>
        internal static string choose_from_gallery {
            get {
                return ResourceManager.GetString("choose_from_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Image.
        /// </summary>
        internal static string choose_image {
            get {
                return ResourceManager.GetString("choose_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close app?.
        /// </summary>
        internal static string closeApp {
            get {
                return ResourceManager.GetString("closeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSED.
        /// </summary>
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code send to.
        /// </summary>
        internal static string codeSendTo {
            get {
                return ResourceManager.GetString("codeSendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee &amp; Juice.
        /// </summary>
        internal static string coffee_juice {
            get {
                return ResourceManager.GetString("coffee_juice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Number.
        /// </summary>
        internal static string communicationNumber {
            get {
                return ResourceManager.GetString("communicationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string companyName {
            get {
                return ResourceManager.GetString("companyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETE.
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string confirm_password {
            get {
                return ResourceManager.GetString("confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        internal static string connection_failed {
            get {
                return ResourceManager.GetString("connection_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string contact_us {
            get {
                return ResourceManager.GetString("contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of Civil Register (copy of residencefor non-Saudis and passport).
        /// </summary>
        internal static string copy_civil_register {
            get {
                return ResourceManager.GetString("copy_civil_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        internal static string country_code {
            get {
                return ResourceManager.GetString("country_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Your Account.
        /// </summary>
        internal static string create_account {
            get {
                return ResourceManager.GetString("create_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create order?.
        /// </summary>
        internal static string createOrder {
            get {
                return ResourceManager.GetString("createOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current and New Password can&apos;t be same..
        /// </summary>
        internal static string current_old_password_matched_validation {
            get {
                return ResourceManager.GetString("current_old_password_matched_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string current_password {
            get {
                return ResourceManager.GetString("current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Orders.
        /// </summary>
        internal static string currentOrdersBtn {
            get {
                return ResourceManager.GetString("currentOrdersBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Details.
        /// </summary>
        internal static string customerAddressDetails {
            get {
                return ResourceManager.GetString("customerAddressDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this card?.
        /// </summary>
        internal static string delete_card {
            get {
                return ResourceManager.GetString("delete_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete address?.
        /// </summary>
        internal static string deleteAddressMsg {
            get {
                return ResourceManager.GetString("deleteAddressMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete product?.
        /// </summary>
        internal static string deleteSellerProductMsg {
            get {
                return ResourceManager.GetString("deleteSellerProductMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        internal static string delivered {
            get {
                return ResourceManager.GetString("delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        internal static string delivery_address {
            get {
                return ResourceManager.GetString("delivery_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Fee.
        /// </summary>
        internal static string delivery_fee {
            get {
                return ResourceManager.GetString("delivery_fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Management System.
        /// </summary>
        internal static string deliveryManagement {
            get {
                return ResourceManager.GetString("deliveryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictance Fee.
        /// </summary>
        internal static string DictanceFee {
            get {
                return ResourceManager.GetString("DictanceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        internal static string driver {
            get {
                return ResourceManager.GetString("driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver on the way.
        /// </summary>
        internal static string Driveronway {
            get {
                return ResourceManager.GetString("Driveronway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        internal static string editsellerproduct {
            get {
                return ResourceManager.GetString("editsellerproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Shop.
        /// </summary>
        internal static string editShop {
            get {
                return ResourceManager.GetString("editShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is empty.
        /// </summary>
        internal static string emptyCart {
            get {
                return ResourceManager.GetString("emptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address.
        /// </summary>
        internal static string enter_address {
            get {
                return ResourceManager.GetString("enter_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter City.
        /// </summary>
        internal static string enter_city {
            get {
                return ResourceManager.GetString("enter_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Confirm Password.
        /// </summary>
        internal static string enter_confirm_password {
            get {
                return ResourceManager.GetString("enter_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Country.
        /// </summary>
        internal static string enter_country {
            get {
                return ResourceManager.GetString("enter_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Current Password.
        /// </summary>
        internal static string enter_current_password {
            get {
                return ResourceManager.GetString("enter_current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Current Password.
        /// </summary>
        internal static string enter_current_password_validation {
            get {
                return ResourceManager.GetString("enter_current_password_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        internal static string enter_email {
            get {
                return ResourceManager.GetString("enter_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email.
        /// </summary>
        internal static string enter_email_validation {
            get {
                return ResourceManager.GetString("enter_email_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Name.
        /// </summary>
        internal static string enter_first_name {
            get {
                return ResourceManager.GetString("enter_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter First name.
        /// </summary>
        internal static string enter_first_name_validation {
            get {
                return ResourceManager.GetString("enter_first_name_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Full Name.
        /// </summary>
        internal static string enter_full_name {
            get {
                return ResourceManager.GetString("enter_full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Landmark.
        /// </summary>
        internal static string enter_landmark {
            get {
                return ResourceManager.GetString("enter_landmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Last Name.
        /// </summary>
        internal static string enter_last_name {
            get {
                return ResourceManager.GetString("enter_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        internal static string enter_name {
            get {
                return ResourceManager.GetString("enter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter name.
        /// </summary>
        internal static string enter_name_validation {
            get {
                return ResourceManager.GetString("enter_name_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password.
        /// </summary>
        internal static string enter_new_password {
            get {
                return ResourceManager.GetString("enter_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter New Password.
        /// </summary>
        internal static string enter_new_password_validation {
            get {
                return ResourceManager.GetString("enter_new_password_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        internal static string enter_password {
            get {
                return ResourceManager.GetString("enter_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        internal static string enter_password_validation {
            get {
                return ResourceManager.GetString("enter_password_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone Number.
        /// </summary>
        internal static string enter_phone_number {
            get {
                return ResourceManager.GetString("enter_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Phone Number.
        /// </summary>
        internal static string enter_phone_number_validation {
            get {
                return ResourceManager.GetString("enter_phone_number_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Time in Minute.
        /// </summary>
        internal static string enter_prepare_time {
            get {
                return ResourceManager.GetString("enter_prepare_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter State.
        /// </summary>
        internal static string enter_state {
            get {
                return ResourceManager.GetString("enter_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Email.
        /// </summary>
        internal static string enter_valid_email_validation {
            get {
                return ResourceManager.GetString("enter_valid_email_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Zipcode.
        /// </summary>
        internal static string enter_zipcode {
            get {
                return ResourceManager.GetString("enter_zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Add On Name.
        /// </summary>
        internal static string enteraddonName {
            get {
                return ResourceManager.GetString("enteraddonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Add On Price.
        /// </summary>
        internal static string enteraddonPrice {
            get {
                return ResourceManager.GetString("enteraddonPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Add On Quantity.
        /// </summary>
        internal static string enteraddonQty {
            get {
                return ResourceManager.GetString("enteraddonQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter card number.
        /// </summary>
        internal static string Entercardnumber {
            get {
                return ResourceManager.GetString("Entercardnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter category.
        /// </summary>
        internal static string enterCategory {
            get {
                return ResourceManager.GetString("enterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter city.
        /// </summary>
        internal static string entercity {
            get {
                return ResourceManager.GetString("entercity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Company Name.
        /// </summary>
        internal static string enterCompanyName {
            get {
                return ResourceManager.GetString("enterCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter country.
        /// </summary>
        internal static string entercountry {
            get {
                return ResourceManager.GetString("entercountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter CVV.
        /// </summary>
        internal static string Entercvv1 {
            get {
                return ResourceManager.GetString("Entercvv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter holder name.
        /// </summary>
        internal static string Enterholdername {
            get {
                return ResourceManager.GetString("Enterholdername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Licence Number.
        /// </summary>
        internal static string enterLicenceNumber {
            get {
                return ResourceManager.GetString("enterLicenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone Number.
        /// </summary>
        internal static string enterPhone {
            get {
                return ResourceManager.GetString("enterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter post code.
        /// </summary>
        internal static string enterpostcode {
            get {
                return ResourceManager.GetString("enterpostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Price.
        /// </summary>
        internal static string enterProducrPrice {
            get {
                return ResourceManager.GetString("enterProducrPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Category Name.
        /// </summary>
        internal static string enterproductcategoryname {
            get {
                return ResourceManager.GetString("enterproductcategoryname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Detail.
        /// </summary>
        internal static string enterProductDetail {
            get {
                return ResourceManager.GetString("enterProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Name.
        /// </summary>
        internal static string enterProductName {
            get {
                return ResourceManager.GetString("enterProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Quantity.
        /// </summary>
        internal static string enterProductQuantity {
            get {
                return ResourceManager.GetString("enterProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Shop Address.
        /// </summary>
        internal static string enterShopAddress {
            get {
                return ResourceManager.GetString("enterShopAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter state.
        /// </summary>
        internal static string enterstate {
            get {
                return ResourceManager.GetString("enterstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter street address.
        /// </summary>
        internal static string enterstreetaddress {
            get {
                return ResourceManager.GetString("enterstreetaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter surname.
        /// </summary>
        internal static string entersurname {
            get {
                return ResourceManager.GetString("entersurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Month.
        /// </summary>
        internal static string ExpiryMonth {
            get {
                return ResourceManager.GetString("ExpiryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Year.
        /// </summary>
        internal static string ExpiryYear {
            get {
                return ResourceManager.GetString("ExpiryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flower Listing.
        /// </summary>
        internal static string flower_listing {
            get {
                return ResourceManager.GetString("flower_listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowers.
        /// </summary>
        internal static string flowers {
            get {
                return ResourceManager.GetString("flowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flower&amp;Candy.
        /// </summary>
        internal static string flowers_candy {
            get {
                return ResourceManager.GetString("flowers_candy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string forgot_password {
            get {
                return ResourceManager.GetString("forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter you phone &amp; we will send you an number that you will allow you to reset your password..
        /// </summary>
        internal static string forgot_password_text {
            get {
                return ResourceManager.GetString("forgot_password_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password?.
        /// </summary>
        internal static string forgot_your_password {
            get {
                return ResourceManager.GetString("forgot_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string full_name {
            get {
                return ResourceManager.GetString("full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you deliverd order?.
        /// </summary>
        internal static string haveyoudelivedrorder {
            get {
                return ResourceManager.GetString("haveyoudelivedrorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you recived order?.
        /// </summary>
        internal static string haveyourecivedorder {
            get {
                return ResourceManager.GetString("haveyourecivedorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string hide {
            get {
                return ResourceManager.GetString("hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to connect. Please check your internet and try again..
        /// </summary>
        internal static string internet_failed_message {
            get {
                return ResourceManager.GetString("internet_failed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmark.
        /// </summary>
        internal static string landmark {
            get {
                return ResourceManager.GetString("landmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence Number.
        /// </summary>
        internal static string licenceNumber {
            get {
                return ResourceManager.GetString("licenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flower&amp;Candy.
        /// </summary>
        internal static string login_text {
            get {
                return ResourceManager.GetString("login_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login first.
        /// </summary>
        internal static string loginfirst {
            get {
                return ResourceManager.GetString("loginfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginUser {
            get {
                return ResourceManager.GetString("loginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        internal static string logout_text {
            get {
                return ResourceManager.GetString("logout_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Card.
        /// </summary>
        internal static string MasterCard {
            get {
                return ResourceManager.GetString("MasterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute prepare time.
        /// </summary>
        internal static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string no_account {
            get {
                return ResourceManager.GetString("no_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        internal static string nodata {
            get {
                return ResourceManager.GetString("nodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note  Details.
        /// </summary>
        internal static string noteDetails {
            get {
                return ResourceManager.GetString("noteDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note For.
        /// </summary>
        internal static string noteFor {
            get {
                return ResourceManager.GetString("noteFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        internal static string notificationpopup_Allow {
            get {
                return ResourceManager.GetString("notificationpopup_Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Allow.
        /// </summary>
        internal static string notificationpopup_DontAllow {
            get {
                return ResourceManager.GetString("notificationpopup_DontAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Flower&amp;Candy&quot; Would Like to Send You Notifications.
        /// </summary>
        internal static string notificationpopup_headertitle {
            get {
                return ResourceManager.GetString("notificationpopup_headertitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications may include alerts, sounds, icon badges..
        /// </summary>
        internal static string notificationpopup_title {
            get {
                return ResourceManager.GetString("notificationpopup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        internal static string offer {
            get {
                return ResourceManager.GetString("offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order accepted by driver.
        /// </summary>
        internal static string Orderacceptedbydriver {
            get {
                return ResourceManager.GetString("Orderacceptedbydriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order accepted by seller.
        /// </summary>
        internal static string Orderacceptedbyseller {
            get {
                return ResourceManager.GetString("Orderacceptedbyseller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order assigned to driver.
        /// </summary>
        internal static string Orderassignedtodriver {
            get {
                return ResourceManager.GetString("Orderassignedtodriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order cancel.
        /// </summary>
        internal static string Ordercancel {
            get {
                return ResourceManager.GetString("Ordercancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order completed.
        /// </summary>
        internal static string Ordercompleted1 {
            get {
                return ResourceManager.GetString("Ordercompleted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order created.
        /// </summary>
        internal static string Ordercreated {
            get {
                return ResourceManager.GetString("Ordercreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        internal static string orderDetails {
            get {
                return ResourceManager.GetString("orderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER NUMBER.
        /// </summary>
        internal static string orderNumber {
            get {
                return ResourceManager.GetString("orderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER ON.
        /// </summary>
        internal static string orderOn {
            get {
                return ResourceManager.GetString("orderOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Pick By Self.
        /// </summary>
        internal static string orderpickbyself {
            get {
                return ResourceManager.GetString("orderpickbyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order rejected by seller.
        /// </summary>
        internal static string Orderrejectedby {
            get {
                return ResourceManager.GetString("Orderrejectedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order rejected by driver.
        /// </summary>
        internal static string Orderrejectedbydriver {
            get {
                return ResourceManager.GetString("Orderrejectedbydriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER STATUS.
        /// </summary>
        internal static string orderStatus {
            get {
                return ResourceManager.GetString("orderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Verification.
        /// </summary>
        internal static string otpVerification {
            get {
                return ResourceManager.GetString("otpVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password not matched.
        /// </summary>
        internal static string password_confirm_password_mismatch_validation {
            get {
                return ResourceManager.GetString("password_confirm_password_mismatch_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUY.
        /// </summary>
        internal static string pay {
            get {
                return ResourceManager.GetString("pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment By.
        /// </summary>
        internal static string paymentBy {
            get {
                return ResourceManager.GetString("paymentBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Address.
        /// </summary>
        internal static string please_enter_address_validation {
            get {
                return ResourceManager.GetString("please_enter_address_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter City.
        /// </summary>
        internal static string please_enter_city_validation {
            get {
                return ResourceManager.GetString("please_enter_city_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Country.
        /// </summary>
        internal static string please_enter_country_validation {
            get {
                return ResourceManager.GetString("please_enter_country_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Full Name.
        /// </summary>
        internal static string please_enter_full_name_validation {
            get {
                return ResourceManager.GetString("please_enter_full_name_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Landmark.
        /// </summary>
        internal static string please_enter_landmark_validation {
            get {
                return ResourceManager.GetString("please_enter_landmark_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter State.
        /// </summary>
        internal static string please_enter_state_validation {
            get {
                return ResourceManager.GetString("please_enter_state_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Zipcode.
        /// </summary>
        internal static string please_enter_zipcode_validation {
            get {
                return ResourceManager.GetString("please_enter_zipcode_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code.
        /// </summary>
        internal static string postcode {
            get {
                return ResourceManager.GetString("postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred For You.
        /// </summary>
        internal static string preferred_for_you {
            get {
                return ResourceManager.GetString("preferred_for_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare time.
        /// </summary>
        internal static string prepare_time {
            get {
                return ResourceManager.GetString("prepare_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Orders.
        /// </summary>
        internal static string previousOrdersBtn {
            get {
                return ResourceManager.GetString("previousOrdersBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Privacy Policy.
        /// </summary>
        internal static string privacy_policy {
            get {
                return ResourceManager.GetString("privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category Name.
        /// </summary>
        internal static string productcategoryname {
            get {
                return ResourceManager.GetString("productcategoryname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Detail.
        /// </summary>
        internal static string productDetail {
            get {
                return ResourceManager.GetString("productDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Details.
        /// </summary>
        internal static string productDetails {
            get {
                return ResourceManager.GetString("productDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productive families.
        /// </summary>
        internal static string productive_families {
            get {
                return ResourceManager.GetString("productive_families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price.
        /// </summary>
        internal static string productPrice {
            get {
                return ResourceManager.GetString("productPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Quantity.
        /// </summary>
        internal static string productquantity {
            get {
                return ResourceManager.GetString("productquantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        internal static string profile_settings {
            get {
                return ResourceManager.GetString("profile_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Phone.
        /// </summary>
        internal static string registerphone {
            get {
                return ResourceManager.GetString("registerphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t get verification code? Resend.
        /// </summary>
        internal static string resendDone {
            get {
                return ResourceManager.GetString("resendDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Cards.
        /// </summary>
        internal static string saved_Cards {
            get {
                return ResourceManager.GetString("saved_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Address.
        /// </summary>
        internal static string searchAddress {
            get {
                return ResourceManager.GetString("searchAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Shop.
        /// </summary>
        internal static string searchShop {
            get {
                return ResourceManager.GetString("searchShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country Code.
        /// </summary>
        internal static string selectCountry {
            get {
                return ResourceManager.GetString("selectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Delivery Address.
        /// </summary>
        internal static string selectDeliveryAddress {
            get {
                return ResourceManager.GetString("selectDeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        internal static string seller {
            get {
                return ResourceManager.GetString("seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Seller Type.
        /// </summary>
        internal static string sellerType {
            get {
                return ResourceManager.GetString("sellerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string shop {
            get {
                return ResourceManager.GetString("shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string sign_up {
            get {
                return ResourceManager.GetString("sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address.
        /// </summary>
        internal static string streetaddress {
            get {
                return ResourceManager.GetString("streetaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Picture.
        /// </summary>
        internal static string take_picture {
            get {
                return ResourceManager.GetString("take_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string terms_conditions {
            get {
                return ResourceManager.GetString("terms_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Agree to Terms &amp; Conditions.
        /// </summary>
        internal static string terms_conditions_validation {
            get {
                return ResourceManager.GetString("terms_conditions_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been accepted and is being prepared.
        /// </summary>
        internal static string Theapplicationhasbeenacceptedandisbeingprepared {
            get {
                return ResourceManager.GetString("Theapplicationhasbeenacceptedandisbeingprepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery specialist is on your way.
        /// </summary>
        internal static string Thedeliveryspecialistisonyourway {
            get {
                return ResourceManager.GetString("Thedeliveryspecialistisonyourway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has been completed.
        /// </summary>
        internal static string Therequesthasbeencompleted {
            get {
                return ResourceManager.GetString("Therequesthasbeencompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Asking Price.
        /// </summary>
        internal static string total_package_price {
            get {
                return ResourceManager.GetString("total_package_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL AMOUNT.
        /// </summary>
        internal static string totalAmount {
            get {
                return ResourceManager.GetString("totalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Order.
        /// </summary>
        internal static string tracking {
            get {
                return ResourceManager.GetString("tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Company Banner.
        /// </summary>
        internal static string uploadCompanyBanner {
            get {
                return ResourceManager.GetString("uploadCompanyBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Company Logo.
        /// </summary>
        internal static string uploadCompanyLogo {
            get {
                return ResourceManager.GetString("uploadCompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Product Image.
        /// </summary>
        internal static string uploadProductImage {
            get {
                return ResourceManager.GetString("uploadProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of Vehicle Form.
        /// </summary>
        internal static string vehicle_from {
            get {
                return ResourceManager.GetString("vehicle_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Image.
        /// </summary>
        internal static string vehicle_image {
            get {
                return ResourceManager.GetString("vehicle_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Card.
        /// </summary>
        internal static string VisaCard {
            get {
                return ResourceManager.GetString("VisaCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order will be confirmed.
        /// </summary>
        internal static string Yourorderwillbeconfirmed {
            get {
                return ResourceManager.GetString("Yourorderwillbeconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your phone number.
        /// </summary>
        internal static string yourPhoneNumber {
            get {
                return ResourceManager.GetString("yourPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to login?.
        /// </summary>
        internal static string youwantlogin {
            get {
                return ResourceManager.GetString("youwantlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        internal static string zipcode {
            get {
                return ResourceManager.GetString("zipcode", resourceCulture);
            }
        }
    }
}
